### ISSUE TITLE
Discussion: Move some ingest scripts to here (astrodbkit)

### ISSUE THREAD

**Issue by kelle** [astrodbtoolkit/AstrodbKit2#63]
Per discussion with @arjunsavel, I still think that some of the most fundamental ingest scripts should live in this package. This makes it possible for those scripts to be improved upon without needing to modify folks' databases.  Example scripts are ingest_publication, ingest_telescope, ingest_source.

**Comment by dr-rodriguez** [comment]
I disagree. This repo stores the database handler code, it is not the SIMPLE codebase- this is meant to serve more than one database and any ingest scripts you write as part of SIMPLE would not be broadly applicable. The documentation alone should be sufficient for users to interface with this and write their own custom ingest scripts.

A better option is a new repo, simple_ingest, or similar that stores the specific scripts for SIMPLE. We can structure that to be pip-installable if we want to make it easier to share.

**Comment by kelle** [comment]
The ingests scripts that I am proposing be here are the ones that are relevant to the tables astrodbkit2 *expects* and/or are in the template. 

I am not advocating that SIMPLE ingest scripts for here, but rather only the most generic scripts that apply to the tables in the template schema.

**Comment by dr-rodriguez** [comment]
But this repo doesn't define any schema at all. It works by the user supplying the object/reference table lists (SIMPLE is a subset of them). You can easily call the primary table `Galaxies` with a primary key `id` and it would work just as well as SIMPLE's use of `Sources` with primary key `source`. For example:
```
db = Database(connection_string,
              reference_tables=['changelog', 'data_requests', 'publications', 'ignore', 'modes',
                                'systems', 'telescopes', 'versions', 'instruments'],
              primary_table='galaxies',
              primary_table_key='id',
              foreign_key='galaxy_id')
```

If you want this in the astrodbkit2 repo, then it should be as methods in the Database class. This isn't a bad idea, but they would be called something like `db.ingest_to_primary_table()`, `db.ingest_to_secondary_table()`, `db.ingest_to_reference_table()`, or similar to abstract away the actual table names. Astrodbkit2 is written to be as close to schema-agnostic as possible. I'm happy to help code these up, but they would need to be generic and users may need their own wrappers for any additional processing.

Alternatively, we can create an astrodb_ingest repo if you want to keep the existing scripts mostly unchanged.

**Comment by kelle** [comment]
Yes, maybe a new repo/package is the answer. My problem is that the template db is not a package! If improvements are made, we want a way for those improvements to be upstreamed and installed without downloading a new database. Maybe a astrodb-scripts repo is the way to go. ("Ingests" is too specific.)

**Comment by kelle** [comment]
@arjunsavel ? What do you think about a new repo with the scripts? That would be the package you install. The template db could be downloaded, but the package is installed and could be updated with improved helper scripts.

**Comment by kelle** [comment]
We could test in either repo. Either install the scripts in the template or clone the template repo as part of the scripts tests.

**Comment by kelle** [comment]
I think the 2nd. Clone the template repo into the scripts repo. 

What we should also sketch out is where we suggest folks store custom scripts

**Comment by kelle** [comment]
This has been resolved. Scripts live in astrodb_utils.
